"""ad user folder scopes and api keys

Revision ID: 14ceceb31869
Revises: 5c1e9a4d7b2f
Create Date: 2026-08-19 10:48:44.805328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ceceb31869'
down_revision: Union[str, None] = '5c1e9a4d7b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_folder_scopes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'folder_id')
    )
    op.create_index(op.f('ix_user_folder_scopes_folder_id'), 'user_folder_scopes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_user_folder_scopes_user_id'), 'user_folder_scopes', ['user_id'], unique=False)
    op.add_column('api_keys', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_column('api_keys', 'user_id')
    op.drop_index(op.f('ix_user_folder_scopes_user_id'), table_name='user_folder_scopes')
    op.drop_index(op.f('ix_user_folder_scopes_folder_id'), table_name='user_folder_scopes')
    op.drop_table('user_folder_scopes')
    # ### end Alembic commands ###
