"""change avatar_asset_id to user id

Revision ID: 2f1e68eb5daf
Revises: 2d20df03562e
Create Date: 2026-08-11 18:50:24.877794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1e68eb5daf'
down_revision: Union[str, None] = '2d20df03562e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_profiles_avatar_asset_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_avatar_user_id'), 'profiles', ['avatar_user_id'], unique=False)
    op.drop_constraint(op.f('profiles_avatar_asset_id_fkey'), 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'avatar_asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_asset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('profiles_avatar_asset_id_fkey'), 'profiles', 'assets', ['avatar_asset_id'], ['id'])
    op.drop_index(op.f('ix_profiles_avatar_user_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_avatar_asset_id'), 'profiles', ['avatar_asset_id'], unique=False)
    op.drop_column('profiles', 'avatar_user_id')
    # ### end Alembic commands ###
