"""add key_encrypted to api_keys

Revision ID: 3b350b3a3bf6
Revises: 14ceceb31869
Create Date: 2026-08-22 21:08:12.985490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b350b3a3bf6'
down_revision: Union[str, None] = '14ceceb31869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'key_encrypted')
    # ### end Alembic commands ###
