"""adding the meta to files for more robust image handling.

Revision ID: 408cdaa725cb
Revises: fc3eea8c796c
Create Date: 2026-06-02 22:43:05.890131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '408cdaa725cb'
down_revision: Union[str, None] = 'fc3eea8c796c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('file_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'file_meta')
    # ### end Alembic commands ###
