"""adding featured slots

Revision ID: 61bb27a30cdc
Revises: cb5bac0111c2
Create Date: 2026-07-18 17:35:13.663622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bb27a30cdc'
down_revision: Union[str, None] = 'cb5bac0111c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_items', sa.Column('featured_level', sa.Integer(), nullable=True))
    op.create_index('ix_feed_items_featured_level', 'feed_items', ['featured_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feed_items_featured_level', table_name='feed_items')
    op.drop_column('feed_items', 'featured_level')
    # ### end Alembic commands ###
