"""adding permission to folders for public consumption of content.

Revision ID: a29d6ed4f430
Revises: 408cdaa725cb
Create Date: 2026-06-11 23:49:45.337059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29d6ed4f430'
down_revision: Union[str, None] = '408cdaa725cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('artifacts', sa.Column('public_magic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_artifacts_public_magic_id'), 'artifacts', ['public_magic_id'], unique=True)
    op.add_column('assets', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assets', sa.Column('public_magic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_assets_public_magic_id'), 'assets', ['public_magic_id'], unique=True)
    op.add_column('folders', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('folders', sa.Column('public_magic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_folders_public_magic_id'), 'folders', ['public_magic_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_public_magic_id'), table_name='folders')
    op.drop_column('folders', 'public_magic_id')
    op.drop_column('folders', 'is_public')
    op.drop_index(op.f('ix_assets_public_magic_id'), table_name='assets')
    op.drop_column('assets', 'public_magic_id')
    op.drop_column('assets', 'is_public')
    op.drop_index(op.f('ix_artifacts_public_magic_id'), table_name='artifacts')
    op.drop_column('artifacts', 'public_magic_id')
    op.drop_column('artifacts', 'is_public')
    # ### end Alembic commands ###
