"""adding the folder and the asset models

Revision ID: c16162a68f93
Revises: 4c7f9554a49f
Create Date: 2026-05-26 05:41:15.588674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16162a68f93'
down_revision: Union[str, None] = '4c7f9554a49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_created_by_id'), 'folders', ['created_by_id'], unique=False)
    op.create_index('ix_folders_name_parent', 'folders', ['name', 'parent_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index('ix_folders_path', 'folders', ['path'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('descendant_of', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['descendant_of'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_created_at', 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_created_by_id'), 'assets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_assets_descendant_of'), 'assets', ['descendant_of'], unique=False)
    op.create_index(op.f('ix_assets_folder_id'), 'assets', ['folder_id'], unique=False)
    op.create_index('ix_assets_folder_mime', 'assets', ['folder_id', 'mime_type'], unique=False)
    op.create_index('ix_assets_mime_type', 'assets', ['mime_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_mime_type', table_name='assets')
    op.drop_index('ix_assets_folder_mime', table_name='assets')
    op.drop_index(op.f('ix_assets_folder_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_descendant_of'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_by_id'), table_name='assets')
    op.drop_index('ix_assets_created_at', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_folders_path', table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index('ix_folders_name_parent', table_name='folders')
    op.drop_index(op.f('ix_folders_created_by_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
