"""adding public feed meta to artifact

Revision ID: cb5bac0111c2
Revises: seed_themes
Create Date: 2026-07-01 06:45:59.273527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5bac0111c2'
down_revision: Union[str, None] = 'seed_themes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id'),
    sa.UniqueConstraint('artifact_id', name='uq_feed_items_artifact_id')
    )
    op.create_index('ix_feed_items_sort_order', 'feed_items', ['sort_order'], unique=False)
    op.create_index('ix_feed_items_updated_at', 'feed_items', ['updated_at'], unique=False)
    op.add_column('artifacts', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'meta')
    op.drop_index('ix_feed_items_updated_at', table_name='feed_items')
    op.drop_index('ix_feed_items_sort_order', table_name='feed_items')
    op.drop_table('feed_items')
    # ### end Alembic commands ###
