"""adapting models for artifacts and assets coexistence

Revision ID: e5f71f68e903
Revises: c16162a68f93
Create Date: 2026-06-01 22:33:35.843978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f71f68e903'
down_revision: Union[str, None] = 'c16162a68f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_created_by_id'), 'artifacts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_artifacts_folder_id'), 'artifacts', ['folder_id'], unique=False)
    op.create_index('ix_artifacts_folder_type', 'artifacts', ['folder_id', 'type'], unique=False)
    op.create_index('ix_artifacts_type', 'artifacts', ['type'], unique=False)
    op.alter_column('assets', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('folders', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assets', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_artifacts_type', table_name='artifacts')
    op.drop_index('ix_artifacts_folder_type', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_folder_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_by_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_created_at', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
