"""add repo ssh keys

Revision ID: f09d9381a58b
Revises: 61bb27a30cdc
Create Date: 2026-07-21 07:32:01.819824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09d9381a58b'
down_revision: Union[str, None] = '61bb27a30cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_ssh_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_ssh_keys_fingerprint'), 'repo_ssh_keys', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_repo_ssh_keys_user_id'), 'repo_ssh_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_ssh_keys_user_id'), table_name='repo_ssh_keys')
    op.drop_index(op.f('ix_repo_ssh_keys_fingerprint'), table_name='repo_ssh_keys')
    op.drop_table('repo_ssh_keys')
    # ### end Alembic commands ###
